### ISSUE TITLE
タイムラインの作成

### ISSUE THREAD

**Issue by temmie0232** [temmie0232/MyApp#12]

**Comment by temmie0232** [comment]
##Todo
- [x] タイムラインのレイアウトを作成
- [ ] 投稿とユーザー名をデータベースから取得 (API)
- [ ] 投稿のコンポーネント(Container)のレイアウトを作成 (本文)
- [ ] 取得した投稿とユーザー名を基に投稿のコンポーネントのインスタンスを作成しColumnで並べる
- [x] 投稿のコンポーネントにユーザー名・ユーザーID・投稿日時の表示を追加
- [x] 投稿日時の表記を ※以下 の様に変更
- [ ] タイムラインの表示される投稿数が0のときレイアウトが崩れるのを修正
- [ ] タイムラインの表示を おすすめ / フォローしてるユーザーのみ に切り替えられるように
- [ ] 更新ボタンの追加
- [ ] いいね機能を追加
- [ ] リポスト機能を追加
- [ ] 返信機能を追加

※
1分以内: たった今
1時間以内: n分前
24時間以内: n時間前
7日以内: n日前
7日以上前: yyyy/mm/dd 形式
